module.exports = {
    "href": "https://api.spotify.com/v1/playlists/5XOYtNYFM0F8930gu1O2YK/tracks?offset=0&limit=100",
    "items": [
      {
        "added_at": "2019-05-01T05:54:43Z",
        "added_by": {
          "external_urls": {
            "spotify": "https://open.spotify.com/user/11146615918"
          },
          "href": "https://api.spotify.com/v1/users/11146615918",
          "id": "11146615918",
          "type": "user",
          "uri": "spotify:user:11146615918"
        },
        "is_local": false,
        "primary_color": null,
        "track": {
          "album": {
            "album_type": "single",
            "artists": [
              {
                "external_urls": {
                  "spotify": "https://open.spotify.com/artist/6hl5k4gLl1p3sjhHcb57t2"
                },
                "href": "https://api.spotify.com/v1/artists/6hl5k4gLl1p3sjhHcb57t2",
                "id": "6hl5k4gLl1p3sjhHcb57t2",
                "name": "Circa Waves",
                "type": "artist",
                "uri": "spotify:artist:6hl5k4gLl1p3sjhHcb57t2"
              }
            ],
            "available_markets": [
              "AD",
              "AE",
              "AR",
              "AT",
              "AU",
              "BE",
              "BG",
              "BH",
              "BO",
              "BR",
              "CA",
              "CH",
              "CL",
              "CO",
              "CR",
              "CY",
              "CZ",
              "DE",
              "DK",
              "DO",
              "DZ",
              "EC",
              "EE",
              "EG",
              "ES",
              "FI",
              "FR",
              "GB",
              "GR",
              "GT",
              "HK",
              "HN",
              "HU",
              "ID",
              "IE",
              "IL",
              "IN",
              "IS",
              "IT",
              "JO",
              "JP",
              "KW",
              "LB",
              "LI",
              "LT",
              "LU",
              "LV",
              "MA",
              "MC",
              "MT",
              "MX",
              "MY",
              "NI",
              "NL",
              "NO",
              "NZ",
              "OM",
              "PA",
              "PE",
              "PH",
              "PL",
              "PS",
              "PT",
              "PY",
              "QA",
              "RO",
              "SA",
              "SE",
              "SG",
              "SK",
              "SV",
              "TH",
              "TN",
              "TR",
              "TW",
              "US",
              "UY",
              "VN",
              "ZA"
            ],
            "external_urls": {
              "spotify": "https://open.spotify.com/album/0Ub1DHTVSrdC3HFKBKSkoD"
            },
            "href": "https://api.spotify.com/v1/albums/0Ub1DHTVSrdC3HFKBKSkoD",
            "id": "0Ub1DHTVSrdC3HFKBKSkoD",
            "images": [
              {
                "height": 640,
                "url": "https://i.scdn.co/image/72a75585563a9c86178bf0ee4fdf1786b505187d",
                "width": 640
              },
              {
                "height": 300,
                "url": "https://i.scdn.co/image/ee5bfd991780a6a67d8af125aa47bbd754be8e9a",
                "width": 300
              },
              {
                "height": 64,
                "url": "https://i.scdn.co/image/7bf1e2b21449f88ea8d85e47f2e618db44a4ef5b",
                "width": 64
              }
            ],
            "name": "Me, Myself and Hollywood / Movies",
            "release_date": "2019-01-30",
            "release_date_precision": "day",
            "total_tracks": 2,
            "type": "album",
            "uri": "spotify:album:0Ub1DHTVSrdC3HFKBKSkoD"
          },
          "artists": [
            {
              "external_urls": {
                "spotify": "https://open.spotify.com/artist/6hl5k4gLl1p3sjhHcb57t2"
              },
              "href": "https://api.spotify.com/v1/artists/6hl5k4gLl1p3sjhHcb57t2",
              "id": "6hl5k4gLl1p3sjhHcb57t2",
              "name": "Circa Waves",
              "type": "artist",
              "uri": "spotify:artist:6hl5k4gLl1p3sjhHcb57t2"
            }
          ],
          "available_markets": [
            "AD",
            "AE",
            "AR",
            "AT",
            "AU",
            "BE",
            "BG",
            "BH",
            "BO",
            "BR",
            "CA",
            "CH",
            "CL",
            "CO",
            "CR",
            "CY",
            "CZ",
            "DE",
            "DK",
            "DO",
            "DZ",
            "EC",
            "EE",
            "EG",
            "ES",
            "FI",
            "FR",
            "GB",
            "GR",
            "GT",
            "HK",
            "HN",
            "HU",
            "ID",
            "IE",
            "IL",
            "IN",
            "IS",
            "IT",
            "JO",
            "JP",
            "KW",
            "LB",
            "LI",
            "LT",
            "LU",
            "LV",
            "MA",
            "MC",
            "MT",
            "MX",
            "MY",
            "NI",
            "NL",
            "NO",
            "NZ",
            "OM",
            "PA",
            "PE",
            "PH",
            "PL",
            "PS",
            "PT",
            "PY",
            "QA",
            "RO",
            "SA",
            "SE",
            "SG",
            "SK",
            "SV",
            "TH",
            "TN",
            "TR",
            "TW",
            "US",
            "UY",
            "VN",
            "ZA"
          ],
          "disc_number": 1,
          "duration_ms": 168745,
          "episode": false,
          "explicit": false,
          "external_ids": {
            "isrc": "GBPVV1802563"
          },
          "external_urls": {
            "spotify": "https://open.spotify.com/track/3VTfaqcmuCTZkKUqvaRQka"
          },
          "href": "https://api.spotify.com/v1/tracks/3VTfaqcmuCTZkKUqvaRQka",
          "id": "3VTfaqcmuCTZkKUqvaRQka",
          "is_local": false,
          "name": "Me, Myself and Hollywood",
          "popularity": 50,
          "preview_url": "https://p.scdn.co/mp3-preview/7fef54f7effa32964bd040cd576a02dbeb8a4db4?cid=774b29d4f13844c495f206cafdad9c86",
          "track": true,
          "track_number": 1,
          "type": "track",
          "uri": "spotify:track:3VTfaqcmuCTZkKUqvaRQka"
        },
        "video_thumbnail": {
          "url": null
        }
      },
      {
        "added_at": "2019-05-01T07:57:57Z",
        "added_by": {
          "external_urls": {
            "spotify": "https://open.spotify.com/user/11146615918"
          },
          "href": "https://api.spotify.com/v1/users/11146615918",
          "id": "11146615918",
          "type": "user",
          "uri": "spotify:user:11146615918"
        },
        "is_local": false,
        "primary_color": null,
        "track": {
          "album": {
            "album_type": "album",
            "artists": [
              {
                "external_urls": {
                  "spotify": "https://open.spotify.com/artist/2ARO60gI5do88ho6azmzab"
                },
                "href": "https://api.spotify.com/v1/artists/2ARO60gI5do88ho6azmzab",
                "id": "2ARO60gI5do88ho6azmzab",
                "name": "Django Django",
                "type": "artist",
                "uri": "spotify:artist:2ARO60gI5do88ho6azmzab"
              }
            ],
            "available_markets": [
              "AD",
              "AE",
              "AR",
              "AT",
              "AU",
              "BE",
              "BG",
              "BH",
              "BO",
              "BR",
              "CA",
              "CH",
              "CL",
              "CO",
              "CR",
              "CY",
              "CZ",
              "DE",
              "DK",
              "DO",
              "DZ",
              "EC",
              "EE",
              "EG",
              "ES",
              "FI",
              "FR",
              "GB",
              "GR",
              "GT",
              "HK",
              "HN",
              "HU",
              "ID",
              "IE",
              "IL",
              "IN",
              "IS",
              "IT",
              "JO",
              "JP",
              "KW",
              "LB",
              "LI",
              "LT",
              "LU",
              "LV",
              "MA",
              "MC",
              "MT",
              "MX",
              "MY",
              "NI",
              "NL",
              "NO",
              "NZ",
              "OM",
              "PA",
              "PE",
              "PH",
              "PL",
              "PS",
              "PT",
              "PY",
              "QA",
              "RO",
              "SA",
              "SE",
              "SG",
              "SK",
              "SV",
              "TH",
              "TN",
              "TR",
              "TW",
              "US",
              "UY",
              "VN",
              "ZA"
            ],
            "external_urls": {
              "spotify": "https://open.spotify.com/album/61rOk6XQluHCZmn5Htw8ET"
            },
            "href": "https://api.spotify.com/v1/albums/61rOk6XQluHCZmn5Htw8ET",
            "id": "61rOk6XQluHCZmn5Htw8ET",
            "images": [
              {
                "height": 640,
                "url": "https://i.scdn.co/image/2fbf0d920ef067f99364d0e3175d2dc323bf178b",
                "width": 640
              },
              {
                "height": 300,
                "url": "https://i.scdn.co/image/2352711d6cd9aa7d94688454ab3436c16a487ab0",
                "width": 300
              },
              {
                "height": 64,
                "url": "https://i.scdn.co/image/50ac21847cbba424c891da466a6df06bd838d46d",
                "width": 64
              }
            ],
            "name": "Marble Skies",
            "release_date": "2018-01-26",
            "release_date_precision": "day",
            "total_tracks": 10,
            "type": "album",
            "uri": "spotify:album:61rOk6XQluHCZmn5Htw8ET"
          },
          "artists": [
            {
              "external_urls": {
                "spotify": "https://open.spotify.com/artist/2ARO60gI5do88ho6azmzab"
              },
              "href": "https://api.spotify.com/v1/artists/2ARO60gI5do88ho6azmzab",
              "id": "2ARO60gI5do88ho6azmzab",
              "name": "Django Django",
              "type": "artist",
              "uri": "spotify:artist:2ARO60gI5do88ho6azmzab"
            }
          ],
          "available_markets": [
            "AD",
            "AE",
            "AR",
            "AT",
            "AU",
            "BE",
            "BG",
            "BH",
            "BO",
            "BR",
            "CA",
            "CH",
            "CL",
            "CO",
            "CR",
            "CY",
            "CZ",
            "DE",
            "DK",
            "DO",
            "DZ",
            "EC",
            "EE",
            "EG",
            "ES",
            "FI",
            "FR",
            "GB",
            "GR",
            "GT",
            "HK",
            "HN",
            "HU",
            "ID",
            "IE",
            "IL",
            "IN",
            "IS",
            "IT",
            "JO",
            "JP",
            "KW",
            "LB",
            "LI",
            "LT",
            "LU",
            "LV",
            "MA",
            "MC",
            "MT",
            "MX",
            "MY",
            "NI",
            "NL",
            "NO",
            "NZ",
            "OM",
            "PA",
            "PE",
            "PH",
            "PL",
            "PS",
            "PT",
            "PY",
            "QA",
            "RO",
            "SA",
            "SE",
            "SG",
            "SK",
            "SV",
            "TH",
            "TN",
            "TR",
            "TW",
            "US",
            "UY",
            "VN",
            "ZA"
          ],
          "disc_number": 1,
          "duration_ms": 266356,
          "episode": false,
          "explicit": false,
          "external_ids": {
            "isrc": "GBMVH1701180"
          },
          "external_urls": {
            "spotify": "https://open.spotify.com/track/3xh94P26FltdD35YhSli5W"
          },
          "href": "https://api.spotify.com/v1/tracks/3xh94P26FltdD35YhSli5W",
          "id": "3xh94P26FltdD35YhSli5W",
          "is_local": false,
          "name": "Marble Skies",
          "popularity": 42,
          "preview_url": "https://p.scdn.co/mp3-preview/346d4a2e2bd2b2d71c5050362930838d1e9d4220?cid=774b29d4f13844c495f206cafdad9c86",
          "track": true,
          "track_number": 1,
          "type": "track",
          "uri": "spotify:track:3xh94P26FltdD35YhSli5W"
        },
        "video_thumbnail": {
          "url": null
        }
      }
    ],
    "limit": 100,
    "next": null,
    "offset": 0,
    "previous": null,
    "total": 2
  }