module.exports = {
    "href": "https://api.spotify.com/v1/playlists/4N1OXgZ51Y55MsWkWkK4xY/tracks?offset=0&limit=100",
    "items": [
      {
        "added_at": "2019-05-01T10:48:34Z",
        "added_by": {
          "external_urls": {
            "spotify": "https://open.spotify.com/user/mattthomaspotify"
          },
          "href": "https://api.spotify.com/v1/users/mattthomaspotify",
          "id": "mattthomaspotify",
          "type": "user",
          "uri": "spotify:user:mattthomaspotify"
        },
        "is_local": false,
        "primary_color": null,
        "track": {
          "album": {
            "album_type": "single",
            "artists": [
              {
                "external_urls": {
                  "spotify": "https://open.spotify.com/artist/6fxyWrfmjcbj5d12gXeiNV"
                },
                "href": "https://api.spotify.com/v1/artists/6fxyWrfmjcbj5d12gXeiNV",
                "id": "6fxyWrfmjcbj5d12gXeiNV",
                "name": "Denzel Curry",
                "type": "artist",
                "uri": "spotify:artist:6fxyWrfmjcbj5d12gXeiNV"
              }
            ],
            "available_markets": [
              "AD",
              "AE",
              "AR",
              "AT",
              "AU",
              "BE",
              "BG",
              "BH",
              "BO",
              "BR",
              "CA",
              "CH",
              "CL",
              "CO",
              "CR",
              "CY",
              "CZ",
              "DE",
              "DK",
              "DO",
              "DZ",
              "EC",
              "EE",
              "EG",
              "ES",
              "FI",
              "FR",
              "GB",
              "GR",
              "GT",
              "HK",
              "HN",
              "HU",
              "ID",
              "IE",
              "IL",
              "IN",
              "IS",
              "IT",
              "JO",
              "JP",
              "KW",
              "LB",
              "LI",
              "LT",
              "LU",
              "LV",
              "MA",
              "MC",
              "MT",
              "MX",
              "MY",
              "NI",
              "NL",
              "NO",
              "NZ",
              "OM",
              "PA",
              "PE",
              "PH",
              "PL",
              "PS",
              "PT",
              "PY",
              "QA",
              "RO",
              "SA",
              "SE",
              "SG",
              "SK",
              "SV",
              "TH",
              "TN",
              "TR",
              "TW",
              "US",
              "UY",
              "VN",
              "ZA"
            ],
            "external_urls": {
              "spotify": "https://open.spotify.com/album/6mxOHdO9aBhSpixGmhrxP3"
            },
            "href": "https://api.spotify.com/v1/albums/6mxOHdO9aBhSpixGmhrxP3",
            "id": "6mxOHdO9aBhSpixGmhrxP3",
            "images": [
              {
                "height": 640,
                "url": "https://i.scdn.co/image/43111daa5d3cc87e038b7ab9c5e0fdf5f9e6e033",
                "width": 640
              },
              {
                "height": 300,
                "url": "https://i.scdn.co/image/34fdf1fa91c8a084d9452b10562b83c90ed229e7",
                "width": 300
              },
              {
                "height": 64,
                "url": "https://i.scdn.co/image/62ccdfe32e20b82a81b26e8cf58503802eb8cbd9",
                "width": 64
              }
            ],
            "name": "Bulls On Parade (triple j Like A Version)",
            "release_date": "2019-03-15",
            "release_date_precision": "day",
            "total_tracks": 1,
            "type": "album",
            "uri": "spotify:album:6mxOHdO9aBhSpixGmhrxP3"
          },
          "artists": [
            {
              "external_urls": {
                "spotify": "https://open.spotify.com/artist/6fxyWrfmjcbj5d12gXeiNV"
              },
              "href": "https://api.spotify.com/v1/artists/6fxyWrfmjcbj5d12gXeiNV",
              "id": "6fxyWrfmjcbj5d12gXeiNV",
              "name": "Denzel Curry",
              "type": "artist",
              "uri": "spotify:artist:6fxyWrfmjcbj5d12gXeiNV"
            }
          ],
          "available_markets": [
            "AD",
            "AE",
            "AR",
            "AT",
            "AU",
            "BE",
            "BG",
            "BH",
            "BO",
            "BR",
            "CA",
            "CH",
            "CL",
            "CO",
            "CR",
            "CY",
            "CZ",
            "DE",
            "DK",
            "DO",
            "DZ",
            "EC",
            "EE",
            "EG",
            "ES",
            "FI",
            "FR",
            "GB",
            "GR",
            "GT",
            "HK",
            "HN",
            "HU",
            "ID",
            "IE",
            "IL",
            "IN",
            "IS",
            "IT",
            "JO",
            "JP",
            "KW",
            "LB",
            "LI",
            "LT",
            "LU",
            "LV",
            "MA",
            "MC",
            "MT",
            "MX",
            "MY",
            "NI",
            "NL",
            "NO",
            "NZ",
            "OM",
            "PA",
            "PE",
            "PH",
            "PL",
            "PS",
            "PT",
            "PY",
            "QA",
            "RO",
            "SA",
            "SE",
            "SG",
            "SK",
            "SV",
            "TH",
            "TN",
            "TR",
            "TW",
            "US",
            "UY",
            "VN",
            "ZA"
          ],
          "disc_number": 1,
          "duration_ms": 269686,
          "episode": false,
          "explicit": true,
          "external_ids": {
            "isrc": "AUAB01900027"
          },
          "external_urls": {
            "spotify": "https://open.spotify.com/track/5FI3HtW6HGrQ0LCOBMbNo3"
          },
          "href": "https://api.spotify.com/v1/tracks/5FI3HtW6HGrQ0LCOBMbNo3",
          "id": "5FI3HtW6HGrQ0LCOBMbNo3",
          "is_local": false,
          "name": "Bulls On Parade - triple j Like A Version",
          "popularity": 54,
          "preview_url": "https://p.scdn.co/mp3-preview/d8aba68ff47892b5c2470850175048fcb17e0289?cid=774b29d4f13844c495f206cafdad9c86",
          "track": true,
          "track_number": 1,
          "type": "track",
          "uri": "spotify:track:5FI3HtW6HGrQ0LCOBMbNo3"
        },
        "video_thumbnail": {
          "url": null
        }
      },
      {
        "added_at": "2019-05-01T10:55:17Z",
        "added_by": {
          "external_urls": {
            "spotify": "https://open.spotify.com/user/11146615918"
          },
          "href": "https://api.spotify.com/v1/users/11146615918",
          "id": "11146615918",
          "type": "user",
          "uri": "spotify:user:11146615918"
        },
        "is_local": false,
        "primary_color": null,
        "track": {
          "album": {
            "album_type": "single",
            "artists": [
              {
                "external_urls": {
                  "spotify": "https://open.spotify.com/artist/0VjbCUP1KCesKWWxgNaOI2"
                },
                "href": "https://api.spotify.com/v1/artists/0VjbCUP1KCesKWWxgNaOI2",
                "id": "0VjbCUP1KCesKWWxgNaOI2",
                "name": "Saving Sebastian",
                "type": "artist",
                "uri": "spotify:artist:0VjbCUP1KCesKWWxgNaOI2"
              }
            ],
            "available_markets": [
              "AD",
              "AE",
              "AR",
              "AT",
              "AU",
              "BE",
              "BG",
              "BH",
              "BO",
              "BR",
              "CA",
              "CH",
              "CL",
              "CO",
              "CR",
              "CY",
              "CZ",
              "DE",
              "DK",
              "DO",
              "DZ",
              "EC",
              "EE",
              "EG",
              "ES",
              "FI",
              "FR",
              "GB",
              "GR",
              "GT",
              "HK",
              "HN",
              "HU",
              "ID",
              "IE",
              "IL",
              "IN",
              "IS",
              "IT",
              "JO",
              "JP",
              "KW",
              "LB",
              "LI",
              "LT",
              "LU",
              "LV",
              "MA",
              "MC",
              "MT",
              "MX",
              "MY",
              "NI",
              "NL",
              "NO",
              "NZ",
              "OM",
              "PA",
              "PE",
              "PH",
              "PL",
              "PS",
              "PT",
              "PY",
              "QA",
              "RO",
              "SA",
              "SE",
              "SG",
              "SK",
              "SV",
              "TH",
              "TN",
              "TR",
              "TW",
              "US",
              "UY",
              "VN",
              "ZA"
            ],
            "external_urls": {
              "spotify": "https://open.spotify.com/album/7EXk77TcP0gVDJUcxSrF7i"
            },
            "href": "https://api.spotify.com/v1/albums/7EXk77TcP0gVDJUcxSrF7i",
            "id": "7EXk77TcP0gVDJUcxSrF7i",
            "images": [
              {
                "height": 640,
                "url": "https://i.scdn.co/image/777c43ebab0dd23b34a6e452698ce11d868fb94f",
                "width": 640
              },
              {
                "height": 300,
                "url": "https://i.scdn.co/image/10b14f05c349774f55a72dc701d80ae77e88d9cd",
                "width": 300
              },
              {
                "height": 64,
                "url": "https://i.scdn.co/image/8f77efbbbd5480b0826c9df2a571ff901adbaa64",
                "width": 64
              }
            ],
            "name": "Cookie.p",
            "release_date": "2016-01-21",
            "release_date_precision": "day",
            "total_tracks": 4,
            "type": "album",
            "uri": "spotify:album:7EXk77TcP0gVDJUcxSrF7i"
          },
          "artists": [
            {
              "external_urls": {
                "spotify": "https://open.spotify.com/artist/0VjbCUP1KCesKWWxgNaOI2"
              },
              "href": "https://api.spotify.com/v1/artists/0VjbCUP1KCesKWWxgNaOI2",
              "id": "0VjbCUP1KCesKWWxgNaOI2",
              "name": "Saving Sebastian",
              "type": "artist",
              "uri": "spotify:artist:0VjbCUP1KCesKWWxgNaOI2"
            }
          ],
          "available_markets": [
            "AD",
            "AE",
            "AR",
            "AT",
            "AU",
            "BE",
            "BG",
            "BH",
            "BO",
            "BR",
            "CA",
            "CH",
            "CL",
            "CO",
            "CR",
            "CY",
            "CZ",
            "DE",
            "DK",
            "DO",
            "DZ",
            "EC",
            "EE",
            "EG",
            "ES",
            "FI",
            "FR",
            "GB",
            "GR",
            "GT",
            "HK",
            "HN",
            "HU",
            "ID",
            "IE",
            "IL",
            "IN",
            "IS",
            "IT",
            "JO",
            "JP",
            "KW",
            "LB",
            "LI",
            "LT",
            "LU",
            "LV",
            "MA",
            "MC",
            "MT",
            "MX",
            "MY",
            "NI",
            "NL",
            "NO",
            "NZ",
            "OM",
            "PA",
            "PE",
            "PH",
            "PL",
            "PS",
            "PT",
            "PY",
            "QA",
            "RO",
            "SA",
            "SE",
            "SG",
            "SK",
            "SV",
            "TH",
            "TN",
            "TR",
            "TW",
            "US",
            "UY",
            "VN",
            "ZA"
          ],
          "disc_number": 1,
          "duration_ms": 212610,
          "episode": false,
          "explicit": false,
          "external_ids": {
            "isrc": "QMPKX1627430"
          },
          "external_urls": {
            "spotify": "https://open.spotify.com/track/40EeHuIBo8bYxN2HW8IbuA"
          },
          "href": "https://api.spotify.com/v1/tracks/40EeHuIBo8bYxN2HW8IbuA",
          "id": "40EeHuIBo8bYxN2HW8IbuA",
          "is_local": false,
          "name": "I Hate Bands That Use Ridiculously Long Song Titles to Name Their Songs, When They Could Have Just Chosen a Phrase from the Chorus... It Really Is That Simple",
          "popularity": 1,
          "preview_url": "https://p.scdn.co/mp3-preview/f025b88278ffb862c5b3e6f89dfe1fad8eb3d6be?cid=774b29d4f13844c495f206cafdad9c86",
          "track": true,
          "track_number": 4,
          "type": "track",
          "uri": "spotify:track:40EeHuIBo8bYxN2HW8IbuA"
        },
        "video_thumbnail": {
          "url": null
        }
      },
      {
        "added_at": "2019-05-01T11:16:11Z",
        "added_by": {
          "external_urls": {
            "spotify": "https://open.spotify.com/user/mynameisjacobreilly"
          },
          "href": "https://api.spotify.com/v1/users/mynameisjacobreilly",
          "id": "mynameisjacobreilly",
          "type": "user",
          "uri": "spotify:user:mynameisjacobreilly"
        },
        "is_local": false,
        "primary_color": null,
        "track": {
          "album": {
            "album_type": "album",
            "artists": [
              {
                "external_urls": {
                  "spotify": "https://open.spotify.com/artist/1TkMNnlmVdWmE2DPzKhZmr"
                },
                "href": "https://api.spotify.com/v1/artists/1TkMNnlmVdWmE2DPzKhZmr",
                "id": "1TkMNnlmVdWmE2DPzKhZmr",
                "name": "P C III",
                "type": "artist",
                "uri": "spotify:artist:1TkMNnlmVdWmE2DPzKhZmr"
              }
            ],
            "available_markets": [
              "AD",
              "AE",
              "AR",
              "AT",
              "AU",
              "BE",
              "BG",
              "BH",
              "BO",
              "BR",
              "CA",
              "CH",
              "CL",
              "CO",
              "CR",
              "CY",
              "CZ",
              "DE",
              "DK",
              "DO",
              "DZ",
              "EC",
              "EE",
              "EG",
              "ES",
              "FI",
              "FR",
              "GB",
              "GR",
              "GT",
              "HK",
              "HN",
              "HU",
              "ID",
              "IE",
              "IL",
              "IN",
              "IS",
              "IT",
              "JO",
              "JP",
              "KW",
              "LB",
              "LI",
              "LT",
              "LU",
              "LV",
              "MA",
              "MC",
              "MT",
              "MX",
              "MY",
              "NI",
              "NL",
              "NO",
              "NZ",
              "OM",
              "PA",
              "PE",
              "PH",
              "PL",
              "PS",
              "PT",
              "PY",
              "QA",
              "RO",
              "SA",
              "SE",
              "SG",
              "SK",
              "SV",
              "TH",
              "TN",
              "TR",
              "TW",
              "US",
              "UY",
              "VN",
              "ZA"
            ],
            "external_urls": {
              "spotify": "https://open.spotify.com/album/3UpU3UWCvlk76ogUJzi40E"
            },
            "href": "https://api.spotify.com/v1/albums/3UpU3UWCvlk76ogUJzi40E",
            "id": "3UpU3UWCvlk76ogUJzi40E",
            "images": [
              {
                "height": 640,
                "url": "https://i.scdn.co/image/45f67184d081639425afe916cb72b5b5292e267e",
                "width": 640
              },
              {
                "height": 300,
                "url": "https://i.scdn.co/image/65c038124c478e971e819eb9ba8f4ac5919f8812",
                "width": 300
              },
              {
                "height": 64,
                "url": "https://i.scdn.co/image/4fac79850520541a41523588ab476ccb2b503e81",
                "width": 64
              }
            ],
            "name": "The Rise and Fall of Bossanova (A 13:23:32 Song)",
            "release_date": "2016-11-01",
            "release_date_precision": "day",
            "total_tracks": 5,
            "type": "album",
            "uri": "spotify:album:3UpU3UWCvlk76ogUJzi40E"
          },
          "artists": [
            {
              "external_urls": {
                "spotify": "https://open.spotify.com/artist/1TkMNnlmVdWmE2DPzKhZmr"
              },
              "href": "https://api.spotify.com/v1/artists/1TkMNnlmVdWmE2DPzKhZmr",
              "id": "1TkMNnlmVdWmE2DPzKhZmr",
              "name": "P C III",
              "type": "artist",
              "uri": "spotify:artist:1TkMNnlmVdWmE2DPzKhZmr"
            }
          ],
          "available_markets": [
            "AD",
            "AE",
            "AR",
            "AT",
            "AU",
            "BE",
            "BG",
            "BH",
            "BO",
            "BR",
            "CA",
            "CH",
            "CL",
            "CO",
            "CR",
            "CY",
            "CZ",
            "DE",
            "DK",
            "DO",
            "DZ",
            "EC",
            "EE",
            "EG",
            "ES",
            "FI",
            "FR",
            "GB",
            "GR",
            "GT",
            "HK",
            "HN",
            "HU",
            "ID",
            "IE",
            "IL",
            "IN",
            "IS",
            "IT",
            "JO",
            "JP",
            "KW",
            "LB",
            "LI",
            "LT",
            "LU",
            "LV",
            "MA",
            "MC",
            "MT",
            "MX",
            "MY",
            "NI",
            "NL",
            "NO",
            "NZ",
            "OM",
            "PA",
            "PE",
            "PH",
            "PL",
            "PS",
            "PT",
            "PY",
            "QA",
            "RO",
            "SA",
            "SE",
            "SG",
            "SK",
            "SV",
            "TH",
            "TN",
            "TR",
            "TW",
            "US",
            "UY",
            "VN",
            "ZA"
          ],
          "disc_number": 1,
          "duration_ms": 15654000,
          "episode": false,
          "explicit": false,
          "external_ids": {
            "isrc": "TCACT1611065"
          },
          "external_urls": {
            "spotify": "https://open.spotify.com/track/0q5lnUuDhlogtYCOubNQhQ"
          },
          "href": "https://api.spotify.com/v1/tracks/0q5lnUuDhlogtYCOubNQhQ",
          "id": "0q5lnUuDhlogtYCOubNQhQ",
          "is_local": false,
          "name": "The Rise and Fall of Bossanova Section IV",
          "popularity": 6,
          "preview_url": "https://p.scdn.co/mp3-preview/6b0778727967beb341bb32f8d50b1a7f540333d9?cid=774b29d4f13844c495f206cafdad9c86",
          "track": true,
          "track_number": 4,
          "type": "track",
          "uri": "spotify:track:0q5lnUuDhlogtYCOubNQhQ"
        },
        "video_thumbnail": {
          "url": null
        }
      }
    ],
    "limit": 100,
    "next": null,
    "offset": 0,
    "previous": null,
    "total": 3
  }